site_name: Apuntes
theme:
  name: material
  logo: assets/kodemia-logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
copyright: Copyright &copy; 2022  made with ♥ for Kodemia community

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sergio-gonzalez-sainz/apuntes-kodemia

repo_url: https://github.com/sergio-gonzalez-sainz/apuntes-kodemia
repo_name: /apuntes-kodemia

extra_css:
  - stylesheets/extra.css

nav:
    - Inicio: 
      - Intenciones: index.md
      - ¿Cómo colaborar?: colaborar.md
      - Markdown Syntax: syntax.md
    - Maquetado: Maquetado/maquetado.md
    - JavaScript:
          - Repaso: Javascript/repaso.md
    - Talleres: 
          - Linux: Talleres/linux.md
          - Git y Github: Talleres/git.md





